In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./cz_sh_hist_data_0823.csv')

In [3]:
data.head()

,robot_id,avg_current_fluctuation_1,avg_current_fluctuation_2,avg_current_fluctuation_3,avg_current_fluctuation_4,avg_current_fluctuation_5,avg_current_fluctuation_6,avg_inst_inst_temperature_1,avg_inst_inst_temperature_2,avg_inst_inst_temperature_3,avg_inst_inst_temperature_4,avg_inst_inst_temperature_5,avg_inst_inst_temperature_6,sum_running_time,sum_running_circles_1,sum_running_circles_2,sum_running_circles_3,sum_running_circles_4,sum_running_circles_5,sum_running_circles_6
0,Zu7210015,2.781092,0.540051,18.260458,0.608959,0.635944,0.582235,39.916282,41.182418,40.487398,48.112420,50.015884,51.216894,10664959,5.841600e+04,5.054600e+04,5.876700e+04,5.951300e+04,2.671500e+04,4.968700e+04
1,Zu7210070,13.655030,16.927033,13.072177,1.492396,1.131061,1.225600,37.633865,41.179264,38.626982,47.255491,48.509642,50.128134,23654346,4.294966e+07,3.405800e+06,5.179013e+06,6.667523e+06,2.357474e+06,3.908958e+06
2,Zu12100040,15.659775,16.907575,15.680950,14.472050,10.996415,13.040550,56.000000,77.023590,49.989335,49.865880,51.065505,51.005055,1318601,1.148824e+06,7.817030e+05,9.691680e+05,1.580378e+06,1.045185e+06,4.305050e+05
3,Zu3100091,1.021896,0.741080,0.698144,0.875400,1.018324,0.731579,47.067980,49.461640,49.634170,47.783485,48.170405,50.116730,13982800,3.768568e+05,3.785132e+05,3.834209e+05,4.146982e+05,4.002506e+05,2.796802e+05
4,Zu7250098,1.954192,0.844716,0.527591,2.030589,2.830409,2.305008,47.836939,44.643746,40.463622,49.171315,50.295569,50.726686,12819108,1.876323e+06,1.552432e+06,1.715363e+06,1.802528e+06,8.015950e+05,1.860704e+06

In [4]:
data.columns

Index(['robot_id', 'avg_current_fluctuation_1', 'avg_current_fluctuation_2',
       'avg_current_fluctuation_3', 'avg_current_fluctuation_4',
       'avg_current_fluctuation_5', 'avg_current_fluctuation_6',
       'avg_inst_inst_temperature_1', 'avg_inst_inst_temperature_2',
       'avg_inst_inst_temperature_3', 'avg_inst_inst_temperature_4',
       'avg_inst_inst_temperature_5', 'avg_inst_inst_temperature_6',
       'sum_running_time', 'sum_running_circles_1', 'sum_running_circles_2',
       'sum_running_circles_3', 'sum_running_circles_4',
       'sum_running_circles_5', 'sum_running_circles_6'],
      dtype='object')

In [5]:
col_list=['robot_id','sum_running_time','avg_inst_inst_temperature_1','sum_running_circles_1',
          'avg_current_fluctuation_1']
data_ans = pd.DataFrame(columns=col_list)

for i in range(1,7):
    col_list_temp = [col.replace('1',str(i)) for col in col_list]
    data_temp = data[col_list_temp]
    data_temp['joint'] = i
    data_temp.columns = col_list+['joint']
    data_ans = pd.concat([data_ans,data_temp])

<ipython-input-5-bcc5fd37f0fb>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp['joint'] = i

In [6]:
data_ans.iloc[2::44,:]

,robot_id,sum_running_time,avg_inst_inst_temperature_1,sum_running_circles_1,avg_current_fluctuation_1,joint
2,Zu12100040,1318601,56.000000,1148824.0,15.659775,1.0
2,Zu12100040,1318601,77.023590,781703.0,16.907575,2.0
2,Zu12100040,1318601,49.989335,969168.0,15.680950,3.0
2,Zu12100040,1318601,49.865880,1580378.0,14.472050,4.0
2,Zu12100040,1318601,51.065505,1045185.0,10.996415,5.0
2,Zu12100040,1318601,51.005055,430505.0,13.040550,6.0

In [7]:
data_ans = data_ans.rename(columns={'avg_inst_inst_temperature_1':'avg_inst_temperature','sum_running_circles_1':'sum_running_circles','avg_current_fluctuation_1':'avg_current_fluctuation'})

In [8]:
data_ans['joint'] = data_ans['joint'].apply(np.int8)

In [9]:
data_ans

,robot_id,sum_running_time,avg_inst_temperature,sum_running_circles,avg_current_fluctuation,joint
0,Zu7210015,10664959,39.916282,5.841600e+04,2.781092,1
1,Zu7210070,23654346,37.633865,4.294966e+07,13.655030,1
2,Zu12100040,1318601,56.000000,1.148824e+06,15.659775,1
3,Zu3100091,13982800,47.067980,3.768568e+05,1.021896,1
4,Zu7250098,12819108,47.836939,1.876323e+06,1.954192,1
...,...,...,...,...,...,...
39,Zu7250797,236612,52.972273,2.566310e+05,10.853033,6
40,Zu7250777,1317937,52.713623,3.934950e+05,10.963644,6
41,Zu7210031,11698161,54.485709,1.778704e+06,0.074330,6
42,Zu7250813,243977,53.551023,2.657760e+05,12.586668,6
43,Zu7210180,11901451,58.454657,6.905070e+05,6.278358,6

In [10]:
data_ans.to_csv('hist_data_0823.csv')